name: FreemansServer
dependencies:
  QBXMLRP2_DART:
    path: ..\..\..\Documents\GitHub\QuickbooksDesktopConnectorDartlang\package\QBXMLRP2_DART
  ansicolor: any
  intl: any
  json_schema: any
  logging: any
  path: any
  sqljocky: 0.10.0
  utf: any
  uuid: 0.2.0
  xml: any
