name: FreemansServer
dependencies:
  QBXMLRP2_DART: 
       path: 'C:\Users\Bryan Brown\Documents\GitHub\QuickbooksDesktopConnectorDartlang\package\QBXMLRP2_DART'
  logging: any
  path: any
  sqljocky: 0.9.0
  utf: any
  uuid: any
  xml: any