name: GenerateScemas
dependencies:
  QBXMLRP2_DART:
    path: ..\..\..\Documents\GitHub\QuickbooksDesktopConnectorDartlang\package\QBXMLRP2_DART
  intl: any
  logging: any
  path: any
  sqljocky: 0.9.0
  utf: any
  uuid: any
  xml: any
  ansicolor: any
  json_schema: any